### ISSUE TITLE
[Feature] Hide bee stings

### ISSUE THREAD

**Issue by ItsProfessional** [Woolyenough/fabric-hide-arrows#2]
Implementation is the exact same as hiding arrows, create a copy of your ArrowsMixin, and instead of mixing into `renderObject` of `StuckArrowsFeatureRenderer`, mix into `renderObject` of `StuckStingersFeatureRenderer` instead

Enough bee stings make the same monstrosity as arrows, although a bit less, so I think it does fit this mod

**Comment by Woolyenough** [comment]
As of now, I'm overseas, which prevents me from implementing this feature at this moment. However, I am curious, though – could you elaborate more on the visual effects of bee stings in Minecraft? I have not come across such information before.

**Comment by Woolyenough** [comment]
Ah, I see. but bee stings do not seem to have the same visibility as arrows when they're stuck in players.
Sorry, but I do not think I'll be adding this feature. However, you are free to fork the repo!
