### ISSUE TITLE
Mixin fails to apply on 1.21.4

### ISSUE THREAD

**Issue by Longie520** [Woolyenough/fabric-hide-arrows#3]
### Game environment

M1 MacBook Pro
Minecraft version 1.21.4 (the issue can date back to 1.21.2, though)
Fabric Loader 0.16.9 with Fabric API 0.110.5 for 1.21.4
Java 21 (bundled Microsoft runtime)

### Steps to reproduce

1. Install FAPI and Hide Arrows on Fabric 1.21.4 (or any 1.21.2+)
2. Launch the game
3. Initialization screen progress bar fails
4. Stuck on initialization screen

[latest.log](https://github.com/user-attachments/files/18005795/latest.log)

**Comment by Woolyenough** [comment]
Thanks for reporting this. I have posted an update which should now support these new Minecraft versions!
